### ISSUE TITLE
Can it be translated into Russian

### ISSUE THREAD

**Issue by Agzam4** [landgreen/physics#17]
I am from Russia, and we use your site very often, can it be translated into Russian?
Can I offer a translation? And what do I need to do for this? (maybe make _Fork_)

Will you make a drop-down list for selecting a language and store the selected language in `localstorage`, or create a new web page:
```
physics:
> notes
  > notes\circuits\components
     > index.html
     > ru.html (translated variant)
  ...
> index.html
> ru.html (translated variant)
  ...

**Comment by landgreen** [comment]
Sorry I'm slow to respond.  I haven't checked Github in a while.

You are welcome to use the site for any purpose you want. A translation sounds great.

I've never made a multi-language page, so I'm open to any suggestions.  I think starting with a separate Russian page makes sense.  Once it's translated  I can add a drop-down selector on the main page.  A local storage option could work too, I've worked with local storage some, and I should be able to put that together.
